/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityBar: typeof import('./components/ActivityBar.vue')['default']
    CodeEditor: typeof import('./components/CodeEditor.vue')['default']
    FileIcon: typeof import('./components/FileIcon.vue')['default']
    FileTree: typeof import('./components/FileTree.vue')['default']
    MonacoTree: typeof import('./components/monaco-tree/MonacoTree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitileBanner: typeof import('./components/TitileBanner.vue')['default']
    TitleBanner: typeof import('./components/TitleBanner.vue')['default']
    TitleTag: typeof import('./components/TitleTag.vue')['default']
  }
}
