/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"contents" | "cover" | "create-epub-2" | "create-epub-3" | "epub-meta" | "eyes" | "image" | "read-book" | "save-file" | "search" | "separator-horizontal" | "separator-vertical" | "separator">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"contents" | "cover" | "create-epub-2" | "create-epub-3" | "epub-meta" | "eyes" | "image" | "read-book" | "save-file" | "search" | "separator-horizontal" | "separator-vertical" | "separator">;
          default: string;
          required: true;
      };
  }>>, {
      name: "contents" | "cover" | "create-epub-2" | "create-epub-3" | "epub-meta" | "eyes" | "image" | "read-book" | "save-file" | "search" | "separator-horizontal" | "separator-vertical" | "separator";
  }>;
  export const svgNames: ["contents", "cover", "create-epub-2", "create-epub-3", "epub-meta", "eyes", "image", "read-book", "save-file", "search", "separator-horizontal", "separator-vertical", "separator"];
  export type SvgName = "contents" | "cover" | "create-epub-2" | "create-epub-3" | "epub-meta" | "eyes" | "image" | "read-book" | "save-file" | "search" | "separator-horizontal" | "separator-vertical" | "separator";
  export default SvgIcon;
}
