/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
import 'vue'
declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: import("vue").DefineComponent<{
        name: {
            type: import("vue").PropType<"contents" | "create-epub-2" | "create-epub-3" | "epub-meta" | "eyes" | "image" | "read-book" | "save-file" | "search">;
            default: string;
            required: true;
        };
    }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
        name: {
            type: import("vue").PropType<"contents" | "create-epub-2" | "create-epub-3" | "epub-meta" | "eyes" | "image" | "read-book" | "save-file" | "search">;
            default: string;
            required: true;
        };
    }>>, {
        name: "contents" | "create-epub-2" | "create-epub-3" | "epub-meta" | "eyes" | "image" | "read-book" | "save-file" | "search";
    }>;
  }
}
